gui:
  authorColors:
    "*": "#b4befe"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#f5e0dc"
      - bold
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f5e0dc"
    defaultFgColor:
      - "#cdd6f4"
    inactiveBorderColor:
      - "#585b70"
    optionsTextColor:
      - "#89b4fa"
    searchingActiveBorderColor:
      - "#f9e2af"
    selectedLineBgColor:
      - "#313244"
    unstagedChangesColor:
      - "#f2cdcd"
