[cmp.active]
fg = "#fab387"

[cmp.border]
fg = "#45475a"

[cmp.inactive]

[[filetype.rules]]
fg = "#94e2d5"
mime = "image/*"

[[filetype.rules]]
fg = "#f9e2af"
mime = "video/*"

[[filetype.rules]]
fg = "#f9e2af"
mime = "audio/*"

[[filetype.rules]]
fg = "#fab387"
mime = "application/zip"

[[filetype.rules]]
fg = "#fab387"
mime = "application/gzip"

[[filetype.rules]]
fg = "#fab387"
mime = "application/x-tar"

[[filetype.rules]]
fg = "#fab387"
mime = "application/x-bzip"

[[filetype.rules]]
fg = "#fab387"
mime = "application/x-bzip2"

[[filetype.rules]]
fg = "#fab387"
mime = "application/x-7z-compressed"

[[filetype.rules]]
fg = "#fab387"
mime = "application/x-rar"

[[filetype.rules]]
fg = "#cdd6f4"
name = "*"

[[filetype.rules]]
fg = "#89b4fa"
name = "*/"

[help.desc]
fg = "#45475a"

[help.footer]
bg = "#585b70"
fg = "#1e1e2e"

[help.hovered]
bg = "#45475a"
bold = true

[help.on]
fg = "#fab387"

[help.run]
fg = "#94e2d5"

[input.border]
fg = "#45475a"

[input.selected]
reversed = true

[input.title]

[input.value]

[mgr]
border_symbol = "│"
[mgr.border_style]
fg = "#45475a"

[mgr.cwd]
fg = "#94e2d5"

[mgr.find_keyword]
fg = "#f9e2af"
italic = true

[mgr.find_position]
bg = "reset"
fg = "#fab387"
italic = true

[mgr.hovered]
bg = "#313244"
fg = "#cdd6f4"

[mgr.marker_copied]
bg = "#f9e2af"
fg = "#f9e2af"

[mgr.marker_cut]
bg = "#f38ba8"
fg = "#f38ba8"

[mgr.marker_selected]
bg = "#94e2d5"
fg = "#94e2d5"

[mgr.preview_hovered]
underline = true

[mode.normal_alt]
bg = "#45475a"
fg = "#cba6f7"

[mode.normal_main]
bg = "#cba6f7"
bold = true
fg = "#1e1e2e"

[mode.select_alt]
bg = "#a6e3a1"
fg = "#585b70"

[mode.select_main]
bg = "#94e2d5"
bold = true
fg = "#585b70"

[mode.unset_main]
bg = "#f38ba8"
bold = true
fg = "#585b70"

[status.overall]
bg = "#1e1e2e"
fg = "#b4befe"

[status.perm_exec]
fg = "#94e2d5"

[status.perm_read]
fg = "#f9e2af"

[status.perm_sep]
fg = "#585b70"

[status.perm_type]
fg = "#89b4fa"

[status.perm_write]
fg = "#f38ba8"

[status.progress_error]
bg = "#1e1e2e"
fg = "#f38ba8"

[status.progress_label]
bold = true
fg = "#585b70"

[status.progress_normal]
bg = "#1e1e2e"
fg = "#1e1e2e"

[status.sep_left]
close = ""
open = ""

[status.sep_right]
close = ""
open = ""

[tabs.active]
bg = "#585b70"
fg = "#f5e0dc"

[tabs.inactive]
bg = "#1e1e2e"
fg = "#585b70"

[tabs.sep_inner]
close = ""
open = ""

[tabs.sep_outer]
close = ""
open = ""

[tasks.border]
fg = "#45475a"

[tasks.hovered]
underline = true

[tasks.title]

[which]
separator = "  "
[which.cand]
fg = "#94e2d5"

[which.desc]
fg = "#fab387"

[which.mask]
bg = "#45475a"

[which.rest]
fg = "#45475a"

[which.separator_style]
fg = "#45475a"
